# New API data pull and process playland
Rebuilding API process ...

In [ ]:
import pandas as pd
import requests

In [2]:
iter_year = 2023 # Start with season start

## Process Game/Team/Player Box Statistics

In [3]:
%run -i "./subroutine/routine_macrodata.py"

## Play-by-play (in development)

In [47]:
# For each game id, pull play-by-play
iter_game = 2023020368

r = requests.get(url='https://api-web.nhle.com/v1/gamecenter/'
                    + str(iter_game) + "/play-by-play")
data = r.json()

In [ ]:
data["rosterSpots"]

In [99]:
playerdata = pd.json_normalize(data["rosterSpots"])
playerdata = playerdata[
    ['teamId', 'playerId', 'positionCode', 'firstName.default', 'lastName.default']
]
playerdata

    teamId  playerId positionCode firstName.default lastName.default
0       15   8471214            L              Alex         Ovechkin
1       54   8474565            D              Alex      Pietrangelo
2       15   8474590            D              John          Carlson
3       54   8475188            D           Brayden           McNabb
4       15   8475311            G             Darcy          Kuemper
5       15   8475324            D              Nick           Jensen
6       15   8475343            C               Nic             Dowd
7       15   8475744            C            Evgeny        Kuznetsov
8       54   8475913            R              Mark            Stone
9       15   8476441            D              Joel        Edmundson
10      54   8476448            C           William         Karlsson
11      54   8476539            R          Jonathan     Marchessault
12      15   8476880            R               Tom           Wilson
13      54   8476905            C          Chandler       Stephenson
14      54   8477018            D               Ben           Hutton
15      54   8477478            L           William          Carrier
16      15   8477511            R           Anthony           Mantha
17      15   8477845            D            Trevor     van Riemsdyk
18      15   8477947            L             Sonny           Milano
19      54   8477964            C              Ivan        Barbashev
20      15   8477979            R           Nicolas       Aube-Kubel
21      54   8478020            R           Michael           Amadio
22      54   8478403            C              Jack           Eichel
23      54   8478434            R            Keegan          Kolesar
24      15   8478440            C             Dylan           Strome
25      54   8478462            C           Nicolas              Roy
26      54   8479353            C             Brett           Howden
27      15   8479359            L              Beck        Malenstyn
28      54   8479980            D           Nicolas            Hague
29      54   8480238            G              Jiri           Patera
30      54   8480313            G             Logan         Thompson
31      54   8480727            D              Zach       Whitecloud
32      15   8480796            D            Martin        Fehervary
33      15   8480873            D            Rasmus           Sandin
34      54   8481032            C              Paul           Cotter
35      54   8481527            D            Kaedan          Korczak
36      15   8481580            C            Connor        McMichael
37      15   8481656            C          Aliaksei           Protas
38      15   8482148            C           Hendrix         Lapierre
39      15   8482411            G            Hunter          Shepard

In [56]:
gamedata = pd.json_normalize(data["plays"])
gamedata

,eventId,period,timeInPeriod,timeRemaining,situationCode,homeTeamDefendingSide,typeCode,typeDescKey,sortOrder,periodDescriptor.number,...,details.committedByPlayerId,details.drawnByPlayerId,details.scoringPlayerId,details.scoringPlayerTotal,details.assist1PlayerId,details.assist1PlayerTotal,details.assist2PlayerId,details.assist2PlayerTotal,details.awayScore,details.homeScore
0,102,1,00:00,20:00,1551,right,520,period-start,8,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,101,1,00:00,20:00,1551,right,502,faceoff,11,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,8,1,00:09,19:51,1551,right,503,hit,12,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,9,1,00:14,19:46,1551,right,503,hit,13,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,10,1,00:18,19:42,1551,right,503,hit,14,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
288,1151,3,19:49,00:11,1451,right,509,penalty,783,3,...,8477478.0,8479359.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
289,479,3,19:49,00:11,1441,right,502,faceoff,786,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
290,1154,3,19:54,00:06,1441,right,506,shot-on-goal,787,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
291,806,3,20:00,00:00,1441,right,521,period-end,788,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
292,810,3,20:00,00:00,1441,right,524,game-end,792,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [76]:
gamedata.columns

Index(['eventId', 'period', 'timeInPeriod', 'timeRemaining', 'situationCode',
       'homeTeamDefendingSide', 'typeCode', 'typeDescKey', 'sortOrder',
       'periodDescriptor.number', 'periodDescriptor.periodType',
       'details.eventOwnerTeamId', 'details.losingPlayerId',
       'details.winningPlayerId', 'details.xCoord', 'details.yCoord',
       'details.zoneCode', 'details.hittingPlayerId', 'details.hitteePlayerId',
       'details.reason', 'details.shotType', 'details.shootingPlayerId',
       'details.goalieInNetId', 'details.awaySOG', 'details.homeSOG',
       'details.blockingPlayerId', 'details.playerId',
       'details.secondaryReason', 'details.typeCode', 'details.descKey',
       'details.duration', 'details.committedByPlayerId',
       'details.drawnByPlayerId', 'details.scoringPlayerId',
       'details.scoringPlayerTotal', 'details.assist1PlayerId',
       'details.assist1PlayerTotal', 'details.assist2PlayerId',
       'details.assist2PlayerTotal', 'details.awayScore', 'details.homeScore'],
      dtype='object')

In [95]:
gamedata["periodDescriptor.periodType"].unique()

array(['REG'], dtype=object)

In [90]:
gamedata["details.duration"].unique()

array([nan,  2.])

In [88]:
gamedata["details.descKey"].unique()

array([nan, 'slashing', 'hooking', 'tripping', 'roughing'], dtype=object)

In [86]:
gamedata['details.homeSOG'].unique()

array([nan,  0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.,
       12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24.,
       25., 26., 27., 28., 29., 30., 31., 32.])

In [82]:
gamedata["details.reason"].unique()

array([nan, 'high-and-wide-left', 'wide-right', 'icing',
       'goalie-stopped-after-sog', 'wide-left', 'offside',
       'puck-in-netting', 'above-crossbar', 'puck-in-benches',
       'puck-in-crowd', 'high-and-wide-right', 'referee-or-linesman',
       'tv-timeout', 'puck-frozen'], dtype=object)